sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
addons:
  postgresql: "9.4"
matrix:
  allow_failures:
    - python: "nightly"
cache: pip
before_script:
  - psql -c 'create database park_api;' -U postgres
  - pip install -e .
  - cp config_travis.ini config.ini
  - python bin/parkapi-setupdb
script:
  - python tests/validate-geojson.py park_api/cities/*.geojson
  - python -m unittest discover tests
